feat: provide junit5 extension for SystemPropertyRule
SDA-SE/sda-dropwizard-commons pull request #755
Opened 2021-01-15 16:49 UTC by eikenilsknopp

2021-01-18 14:51 UTC, RappC requested changes
Although it is missing for the SystemPropertyRule, shouldn't we add documentation about the extension in the `README.md`?

2021-01-19 06:18 UTC, christopher-cudennec commented on sda-commons-server-testing/README.md
> +# JUnit 4
I think level 1 heading for not used intentionally. Could you just adjust the following heading? I.e. "Provided JUnit 4 rules" and later on "Provided JUnit 5 extensions"?

2021-01-19 06:18 UTC, christopher-cudennec commented on sda-commons-server-testing/README.md
> +a JUnit5 test extension to set and unset environment variables before running an integration test.
this should be "system properties" and not "environment variables".

2021-01-19 06:18 UTC, christopher-cudennec commented on sda-commons-server-testing/README.md
> +To use the extension register it to you test class via the JUnit5 `@RegisterExtension`:
"... to youR test ..."

2021-01-19 06:18 UTC, christopher-cudennec commented on sda-commons-server-testing/README.md
> +Set and overwritten values will be reset and set back to their original value once the test has finished.
"reset and set back" sounds duplicated.

2021-01-19 06:18 UTC, christopher-cudennec commented on sda-commons-server-testing/src/main/java/org/sdase/commons/server/testing/SystemPropertyClassExtension.java
> +public class SystemPropertyClassExtension implements BeforeAllCallback, AfterAllCallback {
I think it would be nice to also have a description and copy/paste template here.

2021-01-19 06:18 UTC, christopher-cudennec commented on sda-commons-server-testing/src/test/java/org/sdase/commons/server/testing/SystemPropertyClassExtensionTest.java
> +  static final TestWrapper WRAPPER = new TestWrapper();
What about a better name like "PreAndPostConditions" for class (and the variable)? :)

2021-01-19 11:49 UTC, christopher-cudennec commented on sda-commons-server-testing/README.md
> +    .unsetProperty(ENV_TO_UNSET);
"ENV_" also seems to be a relict from the EnvironmentRule. Can you change the code example? Either use matching constant names or choose any examples Strings that make sense here.

2021-01-19 11:49 UTC, christopher-cudennec commented on sda-commons-server-testing/README.md
> +    .unsetProperty(ENV_TO_UNSET);
Same here.

2021-01-19 12:15 UTC, christopher-cudennec approved these changes
🚲

2021-01-19 12:21 UTC, RappC approved these changes

2021-01-19 12:30 UTC, merged